name: rayn
version: 1.0.0+1
publish_to: none
description: Private Gym.
environment: 
  sdk: '>=2.18.6 <3.0.0'


dependencies: 
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

